# Generated by Django 6.1.1 on 2026-09-12 18:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
        ('officers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_id', models.CharField(blank=True, max_length=30, unique=True)),
                ('category', models.CharField(choices=[('POTHOLE', 'Pothole'), ('ROAD_DAMAGE', 'Road Damage'), ('GARBAGE', 'Garbage'), ('STREETLIGHT', 'Broken Streetlight'), ('WATER_LEAKAGE', 'Water Leakage'), ('DRAINAGE', 'Drainage Problem'), ('ILLEGAL_DUMPING', 'Illegal Dumping'), ('ENCROACHMENT', 'Encroachment'), ('TRAFFIC_SIGNAL', 'Traffic Signal Problem'), ('OTHER', 'Other')], max_length=30)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='complaints/')),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('ward', models.CharField(blank=True, max_length=100, null=True)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=10)),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('ASSIGNED', 'Assigned'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved'), ('VERIFIED', 'Verified'), ('CLOSED', 'Closed'), ('REOPENED', 'Reopened')], default='SUBMITTED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('citizen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints', to='departments.department')),
                ('officer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints', to='officers.officer')),
            ],
        ),
    ]
