# Generated by Django 6.1.1 on 2026-09-18 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0002_alter_complaint_ward'),
        ('complaints', '0003_fix_old_ward_data'),
    ]

    operations = [
    ]
