# Generated by Django 6.1.1 on 2026-09-17 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0002_ward'),
        ('users', '0004_user_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ward',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='departments.ward'),
        ),
    ]
